name: CI - Build Checks (docker/build)

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ✅ Valida configuración de compilación (NO construye la imagen)
      - name: Validate build configuration (call: check)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          call: check

  build-image:
    # Build real solo si los checks pasaron
    needs: build-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # (Opcional) Build real (sin push, solo para validar que construye)
      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: local/docker-checks-demo:ci